replicaCount: 2

image:
  repository: dockerizzz/devops-demo-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: devops.local
      paths:
        - path: /
          pathType: Prefix
