apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-demo-api
  labels:
    app: devops-demo-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-demo-api
  template:
    metadata:
      labels:
        app: devops-demo-api
    spec:
      containers:
      - name: api
        image: ghcr.io/chavanakash/sagility-assignment:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3005
          name: http
        env:
        - name: PORT
          value: "3005"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3005
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3005
          initialDelaySeconds: 5
          periodSeconds: 5